version: "3.8"

services:
  mysql_server:
    container_name: webapp_notes_db
    image: mysql:8.0.33
    environment:
      - MYSQL_DATABASE=webapp_notes
      - MYSQL_USER=dbadmin
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_CONNECT_TIMEOUT=60000
    networks:
      - webapp-notes-network
  app:
    container_name: webapp_notes_app
    image: node:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - /app/node_modules
      - ./scripts/wait-for-it.sh:/wait-for-it.sh
    depends_on:
      - mysql_server
    networks:
      - webapp-notes-network
    command:
      [
        "/wait-for-it.sh",
        "mysql_server:3306",
        "-t",
        "20",
        "--",
        "npm",
        "start"
      ]
networks:
  webapp-notes-network:
    name: webapp-notes-network
